'use client';
import { useState, useEffect, useRef } from 'react';
import { flushSync } from 'react-dom';
import { ArrowRight, BookOpen, Check, ChevronRight, Lightbulb, Sparkles, RotateCcw, Pencil, MoveUpRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Input } from '@/components/ui/input';

type Problem = {expression:string;question:string;answer:number;display:string;hint:string;steps:[string,string][];note:string;visual?:boolean};
const topics = [
 {name:'Fractions',symbol:'¾',description:'Parts of a whole',color:'purple'},
 {name:'Decimals',symbol:'.5',description:'Make every digit count',color:'blue'},
 {name:'Ratios & percents',symbol:'%',description:'Compare and connect',color:'orange'},
 {name:'Equations',symbol:'x',description:'Find the missing piece',color:'pink'},
 {name:'Geometry',symbol:'△',description:'Explore shapes & space',color:'green'},
 {name:'Statistics',symbol:'▥',description:'Find the story in data',color:'yellow'}
];
function simplify(a:number,b:number){let x=a,y=b;while(y){[x,y]=[y,x%y]}return b/x===1?String(a/x):`${a/x}/${b/x}`;}
export function makeProblem(topic:number,n:number):Problem {
 const k=n%9;
 if(topic===0){const a=k+2,b=k+3;return {expression:`${a}/4 + ${b}/8`,question:'Add the fractions. Simplify your answer if you can.',answer:(2*a+b)/8,display:simplify(2*a+b,8),hint:'The pieces need to be the same size. Change fourths into eighths first.',steps:[['Find a common denominator','4 and 8 share a multiple: 8. We will use eighths.'],['Make equivalent fractions',`${a}/4 = (${a} × 2)/(4 × 2) = ${a*2}/8. The value stays the same.`],['Add the numerators',`${a*2}/8 + ${b}/8 = ${a*2+b}/8. Keep the denominator because the pieces are still eighths.`]],note:'Multiply the top and bottom by the same number to make an equivalent fraction.',visual:k===0};}
 if(topic===1){let a=2.4+k,b=1.35;return {expression:`${a.toFixed(1)} + 1.35`,question:'Add the decimals.',answer:Math.round((a+b)*100)/100,display:(a+b).toFixed(2),hint:'Line up the decimal points. Write 2.4 as 2.40, for example.',steps:[['Line up place values',`Write ${a.toFixed(1)} as ${a.toFixed(2)} so both numbers have hundredths.`],['Add from right to left',`Add hundredths, then tenths, then ones. ${a.toFixed(2)} + 1.35 = ${(a+b).toFixed(2)}.`],['Check the size',`Your answer should be a little more than ${a.toFixed(1)} + 1.`]],note:'Zeros at the end of a decimal do not change its value.'};}
 if(topic===2){let p=20+k*5;return {expression:`${p}% of 80`,question:'Find the percentage of the whole.',answer:p*.8,display:String(p*.8),hint:'Percent means “out of 100.” Turn the percent into a decimal.',steps:[['Write the percent as a decimal',`${p}% = ${p}/100 = ${p/100}.`],['Multiply by the whole',`${p/100} × 80 = ${p*.8}.`],['Check your thinking',`50% of 80 is 40. Your result should be ${p<50?'less than':p===50?'equal to':'greater than'} 40.`]],note:'“Of” tells you to multiply when finding a percentage.'};}
 if(topic===3){let a=7+k,b=19+k*2;return {expression:`x + ${a} = ${b}`,question:'What value of x makes this equation true?',answer:b-a,display:`x = ${b-a}`,hint:`Undo addition by subtracting ${a} from both sides.`,steps:[['Keep both sides balanced',`Subtract ${a} from each side: x + ${a} − ${a} = ${b} − ${a}.`],['Simplify',`x = ${b-a}.`],['Check by substituting',`${b-a} + ${a} = ${b}. Both sides match!`]],note:'Whatever you do to one side of an equation, do to the other side.'};}
 if(topic===4){let b=8+k,h=5;return {expression:`b = ${b} cm, h = ${h} cm`,question:'Find the area of a triangle with this base and perpendicular height.',answer:b*h/2,display:`${b*h/2} cm²`,hint:'A triangle is half of a rectangle with the same base and height.',steps:[['Choose the formula','Area of a triangle = ½ × base × perpendicular height.'],['Substitute the measurements',`A = ½ × ${b} × ${h}.`],['Calculate the area',`A = ${b*h}/2 = ${b*h/2} cm². Area is measured in square units.`]],note:'Use the perpendicular height, which meets the base at a right angle.'};}
 let values=[4+k,6+k,8+k,10+k];return {expression:values.join(', '),question:'Find the mean of these four numbers.',answer:7+k,display:String(7+k),hint:'Add all the values, then divide by how many values there are.',steps:[['Add all the values',`${values.join(' + ')} = ${28+4*k}.`],['Count the values','There are 4 numbers in this data set.'],['Divide the total by the count',`${28+4*k} ÷ 4 = ${7+k}. This is the mean.`]],note:'The mean is the amount each value would have if the total were shared equally.'};
}
export function parseAnswer(s:string){s=s.trim();if(/^-?\d+\s+\d+\/\d+$/.test(s)){const [w,f]=s.split(/\s+/);const [a,b]=f.split('/').map(Number);return b?Number(w)+(Number(w)<0?-1:1)*a/b:NaN;}if(/^-?\d+(\.\d+)?\s*\/\s*-?\d+(\.\d+)?$/.test(s)){const [a,b]=s.split('/').map(Number);return b?a/b:NaN;}return /^-?(\d+(\.\d*)?|\.\d+)$/.test(s)?Number(s):NaN;}
export default function Home(){
 const [topic,setTopic]=useState(0),[index,setIndex]=useState(0),[answer,setAnswer]=useState(''),[feedback,setFeedback]=useState(''),[hint,setHint]=useState(false),[solution,setSolution]=useState(false),[mode,setMode]=useState('practice');
 const p=makeProblem(topic,index); const reset=()=>{setAnswer('');setFeedback('');setHint(false);setSolution(false)};
 const current=useRef(p);current.current=p;
 useEffect(()=>{type Tool={name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown};const context=(document as Document & {modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'show_math_solution',description:'Reveal the step-by-step solution to the currently displayed math problem.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object.');flushSync(()=>setSolution(true));return {problem:current.current.expression,answer:current.current.display,steps:current.current.steps};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return ()=>lifecycle.abort();},[]);
 function check(){let value=parseAnswer(answer);setFeedback(!Number.isFinite(value)?'Enter a number, fraction (like 3/4), or mixed number (like 1 1/4).':Math.abs(value-p.answer)<0.000001?'You got it! Nice work.':'Not quite yet. Try a hint, or work through the solution.');}
 return <div className="site"><header className="header"><a className="brand" href="/" aria-label="Math is fun home"><span className="brand-icon">m<span>✦</span></span>math is <b>fun</b><span className="brand-dot">.</span></a><div className="header-note"><BookOpen size={17}/> A little practice. A lot of possibility.</div><span className="grade">GRADE 6 <Sparkles size={15}/></span></header>
 <main><section className="intro"><div><div className="eyebrow"><span/> YOUR DAILY DOSE OF DISCOVERY</div><h1>Big ideas. <span>Small steps.</span></h1><p>Pick a topic. Give it a try. Let’s figure it out together.</p></div><div className="intro-note"><span className="note-star">✳</span><span>You don’t have to be fast.<br/><b>You just have to be curious.</b></span></div></section>
 <section aria-label="Choose a math topic" className="topics">{topics.map((t,i)=><button key={t.name} onClick={()=>{setTopic(i);setIndex(0);reset();}} className={`topic ${t.color} ${topic===i?'selected':''}`} aria-pressed={topic===i}><span className="topic-top"><span className="symbol">{t.symbol}</span>{topic===i?<span className="selected-check"><Check size={12}/></span>:<MoveUpRight size={15}/>}</span><strong>{t.name}</strong><small>{t.description}</small></button>)}</section>
 <section className="work-section"><div className="section-title"><h2>Let’s work on {topics[topic].name.toLowerCase()}<span>✦</span></h2><span>ONE STEP AT A TIME</span></div><div className="workspace"><article className="problem-card"><div className="problem-toolbar"><Tabs value={mode} onValueChange={v=>{setMode(String(v));reset();}}><TabsList className="mode-tabs"><TabsTrigger value="practice"><Pencil size={15}/>Your turn</TabsTrigger><TabsTrigger value="learn"><BookOpen size={15}/>Learn with me</TabsTrigger></TabsList></Tabs><span className="problem-count">PROBLEM {String(index+1).padStart(2,'0')}</span></div><div className="problem-body"><span className="pill">{topics[topic].name}</span><h3>{p.question}</h3><div className={`equation ${topic>3?'smaller':''}`}>{topic===0?<><span className="fraction"><span>{index%9+2}</span><span>4</span></span><span className="operator">+</span><span className="fraction"><span>{index%9+3}</span><span>8</span></span><span className="operator">=</span><span className="unknown">?</span></>:p.expression}</div>
 {mode==='practice'&&<form onSubmit={e=>{e.preventDefault();check();}}><label htmlFor="answer">Your answer{topic===4?' (in cm²)':''}</label><div className="answer-row"><Input id="answer" value={answer} onChange={e=>{setAnswer(e.target.value);setFeedback('');}} placeholder={topic===0?'e.g. 3/4':'Type your answer'} autoComplete="off" className="answer-input"/><Button type="submit" className="primary-button">Check answer<ArrowRight size={17}/></Button></div><p className="input-note">{topic===0?'Fractions, mixed numbers, and decimals all work.':'Take your time. You can work it out on paper, too.'}</p><p className={`feedback ${feedback.startsWith('You got')?'correct':''}`} role="status">{feedback}</p></form>}
 {hint&&<div className="hint-box" role="status"><Lightbulb size={19}/>{p.hint}</div>}
 {(solution||mode==='learn')&&<div className="solution"><h4>Let’s solve it together</h4>{p.steps.map(([title,body],i)=><div className="step" key={title}><span>{i+1}</span><div><b>{title}</b><p>{body}</p></div></div>)}<div className="final-answer"><Check size={18}/> Answer: {p.display}</div></div>}
 </div><footer className="problem-footer"><div><Button variant="ghost" onClick={()=>setHint(!hint)}><Lightbulb size={17}/>{hint?'Hide hint':'Need a hint?'}</Button>{mode==='practice'&&<Button variant="ghost" onClick={()=>setSolution(!solution)}>{solution?'Hide solution':'Show solution'}<ChevronRight size={16}/></Button>}</div><Button variant="ghost" onClick={()=>{setIndex(index+1);reset();}}><RotateCcw size={16}/>New problem</Button></footer></article>
 <aside className="learning-card"><div className="learning-label"><span><Lightbulb size={17}/></span>THE BIG IDEA</div><h3>{topic===0?'Same whole.\nDifferent pieces.':topic===1?'A place for\nevery digit.':topic===2?'A part of\nthe whole.':topic===3?'Keep it\nin balance.':topic===4?'Think outside\nthe square.':'Every number\nhas a story.'}</h3>{topic===0?<><p>Before you add fractions, make sure the pieces are the same size.</p><div className="fraction-demo"><div><span>½</span><div className="bar halves"><i/><i/></div></div><div><span>⁴⁄₈</span><div className="bar eighths">{Array.from({length:8},(_,i)=><i key={i}/>)}</div></div><small>Same amount. More pieces.</small></div></>:<p>{p.note}</p>}<div className="remember"><span>↳</span><p><b>Remember</b>{topic===0?'Add the numerators. Keep the common denominator.':p.hint}</p></div><span className="card-doodle" aria-hidden="true">{topics[topic].symbol}</span></aside></div></section><div className="bottom-note"><Sparkles size={17}/><p>Mistakes are proof that you’re learning. Keep going!</p></div></main><footer className="site-footer"><span>math is fun.</span><p>Made for curious sixth-grade minds.</p><span>Little by little adds up. ↗</span></footer></div>
}
